apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mhbw3dzv3-python
  janus-idp.io/tekton: mhbw3dzv3-python
  backstage.io/kubernetes-id: mhbw3dzv3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mhbw3dzv3-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
