apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mhbw3dzv3-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:f4bb806f58a176374b29c81988a9e26ef187e62f@sha256:d2b61899a3519b472764bb6a2f5bdbb854a1b0c46b06ac0195af54f389663538
          name: container-image
